name: Feature Request
description: Request a new feature or enhancement
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the feature you'd like to see!
    validations:
      required: true
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What alternatives have you considered?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0